export const FETCH_FEEDBACK_QUESTIONS_REQUEST =
	'FETCH_FEEDBACK_QUESTIONS_REQUEST'
export const FETCH_FEEDBACK_QUESTIONS_SUCCESS =
	'FETCH_FEEDBACK_QUESTIONS_SUCCESS'
export const FETCH_FEEDBACK_QUESTIONS_FAILURE =
	'FETCH_FEEDBACK_QUESTIONS_FAILURE'
export const SAVE_FEEDBACK_ANSWERS_REQUEST = 'SAVE_FEEDBACK_ANSWERS_REQUEST'
export const SAVE_FEEDBACK_ANSWERS_SUCCESS = 'SAVE_FEEDBACK_ANSWERS_SUCCESS'
export const SAVE_FEEDBACK_ANSWERS_FAILURE = 'SAVE_FEEDBACK_ANSWERS_FAILURE'
