export const FETCH_MY_ROUNDS_REQUEST = 'FETCH_MY_ROUNDS_REQUEST'
export const FETCH_MY_ROUNDS_FAILURE = 'FETCH_MY_ROUNDS_FAILURE'
export const FETCH_MY_ROUNDS_SUCCESS = 'FETCH_MY_ROUNDS_SUCCESS'

export const JOIN_ROUND_REQUEST = 'JOIN_ROUND_REQUEST'
export const JOIN_ROUND_FAILURE = 'JOIN_ROUND_FAILURE'
export const JOIN_ROUND_SUCCESS = 'JOIN_ROUND_SUCCESS'

export const RESIGN_ROUND_REQUEST = 'RESIGN_ROUND_REQUEST'
export const RESIGN_ROUND_SUCCESS = 'RESIGN_ROUND_SUCCESS'
export const RESIGN_ROUND_FAILURE = 'RESIGN_ROUND_FAILURE'
