export const SET_PROFILE_INFO = 'SET_PROFILE_INFO'

export const FETCH_MATCHING_QUESTIONS_REQUEST =
	'FETCH_MATCHING_QUESTIONS_REQUEST'
export const FETCH_MATCHING_QUESTIONS_SUCCESS =
	'FETCH_MATCHING_QUESTIONS_SUCCESS'
export const FETCH_MATCHING_QUESTIONS_FAILURE =
	'FETCH_MATCHING_QUESTIONS_FAILURE'

export const SAVE_MATCHING_ANSWERS_REQUEST = 'SAVE_MATCHING_ANSWERS_REQUEST'
export const SAVE_MATCHING_ANSWERS_SUCCESS = 'SAVE_MATCHING_ANSWERS_SUCCESS'
export const SAVE_MATCHING_ANSWERS_FAILURE = 'SAVE_MATCHING_ANSWERS_FAILURE'
